# Generated by Django 3.2.3 on 2022-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='NAME')),
                ('password', models.CharField(max_length=32, verbose_name='PASSWD')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Established Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
    ]
