# Generated by Django 3.2.3 on 2022-02-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Our_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='students',
        ),
    ]
